### ISSUE TITLE
[BUG] Traceback for --get-sriov and --get-bios-attribute on Dell R740XD

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/badfish#334]
We are getting tracebacks with both RPM (system python 3.10) and freshly pulled podman container (python 3.9) for the following commands on Dell R740XD systems for the following commands:  `--get-sriov` and `--get-bios-attribute`

```
# podman run -it --rm --dns 10.1.36.2 quay.io/quads/badfish -H mgmt-e25-h11-740xd.example.com -u quads -p ****** --get-sriov
 
Traceback (most recent call last):
  File "/usr/local/bin/badfish", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/src/badfish/main.py", line 2385, in main
    _host, result = loop.run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/src/badfish/main.py", line 2001, in execute_badfish
    badfish = await badfish_factory(
  File "/usr/local/lib/python3.9/site-packages/src/badfish/main.py", line 40, in badfish_factory
    await badfish.init()
  File "/usr/local/lib/python3.9/site-packages/src/badfish/main.py", line 71, in init
    self.session_uri = await self.find_session_uri()
  File "/usr/local/lib/python3.9/site-packages/src/badfish/main.py", line 482, in find_session_uri
    data = json.loads(raw.strip())
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
# badfish -H mgmt-e25-h11-740xd.example.com -u quads -p ******* --get-sriov
Traceback (most recent call last):
  File "/usr/bin/badfish", line 33, in <module>
    sys.exit(load_entry_point('badfish==1.0.2', 'console_scripts', 'badfish')())
  File "/usr/lib/python3.10/site-packages/badfish/main.py", line 2430, in main
    _host, result = loop.run_until_complete(
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/badfish/main.py", line 2023, in execute_badfish
    badfish = await badfish_factory(
  File "/usr/lib/python3.10/site-packages/badfish/main.py", line 39, in badfish_factory
    await badfish.init()
  File "/usr/lib/python3.10/site-packages/badfish/main.py", line 71, in init
    self.session_uri = await self.find_session_uri()
  File "/usr/lib/python3.10/site-packages/badfish/main.py", line 448, in find_session_uri
    data = json.loads(raw.strip())
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
-=>>rpm -qa | grep badfish
python3-badfish-1.0.2-git.20220916_141252.fc36.noarch
```

```
# badfish -H mgmt-e25-h11-740xd.example.com -u quads -p ****** --get-bios-attribute
Traceback (most recent call last):
  File "/usr/bin/badfish", line 33, in <module>
    sys.exit(load_entry_point('badfish==1.0.2', 'console_scripts', 'badfish')())
  File "/usr/lib/python3.10/site-packages/badfish/main.py", line 2430, in main
    _host, result = loop.run_until_complete(
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/badfish/main.py", line 2023, in execute_badfish
    badfish = await badfish_factory(
  File "/usr/lib/python3.10/site-packages/badfish/main.py", line 39, in badfish_factory
    await badfish.init()
  File "/usr/lib/python3.10/site-packages/badfish/main.py", line 71, in init
    self.session_uri = await self.find_session_uri()
  File "/usr/lib/python3.10/site-packages/badfish/main.py", line 448, in find_session_uri
    data = json.loads(raw.strip())
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by k3nd1k** [comment]
Tried replicating this and couldn't do so. Either with the RPM package or Podman.

With this environment:
```
❯ python --version 
Python 3.10.2
```
```
❯ rpm -qa | grep badfish
python3-badfish-1.0.2-git.20221215_154355.fc35.noarch
```
^^^ The current package version.
The command `--get-sriov` outputs the supposed log/value when making a request to a R740XD.
```
❯ badfish --host mgmt-e00-h00-740xd.example.com -u *********** -p *********** --get-sriov
- INFO     - Enabled
```

This issue can be probably be closed as it is unable to be reproduced.
