### ISSUE TITLE
[BUG] Latest RPM Build fails when trying any kind of variation of `--boot-to` on R630

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/badfish#407]
I know Dell R630 are very old and we may not be able to support this but:

```
-=>>badfish -H mgmt-f28-h24-000-r630.example.com -u root -p XXXXXX  --boot-to NIC.Slot.2-1-1 
Traceback (most recent call last):
  File "/usr/bin/badfish", line 33, in <module>
    sys.exit(load_entry_point('badfish==1.0.2', 'console_scripts', 'badfish')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/badfish/main.py", line 2943, in main
    _host, result = loop.run_until_complete(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/badfish/main.py", line 2468, in execute_badfish
    badfish = await badfish_factory(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/badfish/main.py", line 41, in badfish_factory
    await badfish.init()
  File "/usr/lib/python3.12/site-packages/badfish/main.py", line 73, in init
    self.session_uri = await self.find_session_uri()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/badfish/main.py", line 459, in find_session_uri
    data = json.loads(raw.strip())
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
-=>>badfish -H mgmt-f28-h24-000-r630.example.com -u root -p XXXXX  -i ~/git_modules/badfish-self/config/idrac_interfaces.yml --boot-to-type foreman
Traceback (most recent call last):
  File "/usr/bin/badfish", line 33, in <module>
    sys.exit(load_entry_point('badfish==1.0.2', 'console_scripts', 'badfish')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/badfish/main.py", line 2943, in main
    _host, result = loop.run_until_complete(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/badfish/main.py", line 2468, in execute_badfish
    badfish = await badfish_factory(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/badfish/main.py", line 41, in badfish_factory
    await badfish.init()
  File "/usr/lib/python3.12/site-packages/badfish/main.py", line 73, in init
    self.session_uri = await self.find_session_uri()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/badfish/main.py", line 459, in find_session_uri
    data = json.loads(raw.strip())
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sadsfae** [comment]
Ok this is not a bug, `racadm set iDRAC.webserver.HostHeaderCheck ` needs to be set for this to work right, apparently this can get reset after a firmware update.
